title: ControlShift
email: talk@controlshiftlabs.com
description: ControlShift is a set of web tools that helps your organization build community, leadership, and real power among your members.
baseurl: ""
url: "https://www.controlshiftlabs.com/"
theme_color: '#0f91c2'
relative_permalinks: false

languages: ["en"]
ampdir: amp

### Segment
segment: Bzk4BmiFef6VNuKJRAqXV6zdubV3fnRs

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - jekyll-multiple-languages-plugin
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - images
  - LICENSE
  - package.json
  - README.md
  - OLD_README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
include:
  - _headers
