title: ControlShift
email: talk@controlshiftlabs.com
description: ControlShift is the best software for putting people at the center of your campaigns with distributed events, local groups, and member-led petitions.
baseurl: ""
url: "https://www.controlshiftlabs.com"
theme_color: '#0f91c2'
relative_permalinks: false
image: /assets/images/people.png

twitter:
  username: controlshiftlab
  card: summary
facebook:
  publisher: https://www.facebook.com/controlshiftlabs
languages: ["en"]
pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  permalink: "/blog/:num/"
  title: ':title - page :num'
  sort_reverse: true
feed:
  posts_limit: 20

autopages:
  enabled: false

collections:
  resources:
    output: true
  details:
    output: true

jekyll_get:
  - data: changelogs
    json: 'https://controlshift-changelog.herokuapp.com/changelogs/feed'
  - data: changelog_months
    json: 'https://controlshift-changelog.herokuapp.com/changelogs/feed_months'


### Segment
segment: Bzk4BmiFef6VNuKJRAqXV6zdubV3fnRs

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-include-cache

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - _src
  - images
  - functions
  - LICENSE
  - netlify.toml
  - package.json
  - Rakefile
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - icon.png
  - .idea
  - .git
include:
  - _headers
  - _redirects
