title: ControlShift
email: talk@controlshiftlabs.com
description: ControlShift is a set of web tools that helps your organization build community, leadership, and real power among your members.
baseurl: ""
url: "https://www.controlshiftlabs.com"
theme_color: '#0f91c2'
relative_permalinks: false

languages: ["en"]
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  collection: 'posts'
  per_page: 10
  permalink: "/blog/:num/"
  title: ':title - page :num'
  sort_reverse: true
feed:
  posts_limit: 20

collections:
  resources:
    output: true


### Segment
segment: Bzk4BmiFef6VNuKJRAqXV6zdubV3fnRs

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-include-cache

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - _src
  - images
  - LICENSE
  - netlify.toml
  - package.json
  - Rakefile
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - icon.png
  - .idea
  - .git
include:
  - _headers
  - _redirects
