backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'img/uploads'
public_folder: '/img/uploads'
publish_mode: editorial_workflow
collections:
  - name: 'blog'
    create: true
    label: 'Blog'
    folder: '_posts/'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Author', name: 'author', widget: 'string', required: false  }
      - { label: 'Featured Image', name: 'featured_image', widget: 'string', required: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'resources'
    create: true
    label: 'Resources'
    folder: '_resources/'
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'resource' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Tease Title', name: 'tease_title', widget: 'string' }
      - { label: 'Tease Blurb', name: 'tease_blurb', widget: 'text' }
      - { label: 'Tease Image URL', name: 'tease_image_url', widget: 'string' }
      - { label: 'Resource Download URL', name: 'resource_url', widget: 'string'}
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'details'
    create: true
    label: 'Details'
    folder: '_details/'
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'detail' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
# local_backend: true
