backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
publish_mode: editorial_workflow
collections:
  - name: 'blog'
    create: true
    label: 'Blog'
    folder: '_posts/'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Featured Image', name: 'featured_image', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
# local_backend: true
